# Default values for person-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: raymasson/person-api
  tag: 1.0.0
  pullPolicy: IfNotPresent
service:
  name: service
  type: NodePort
  externalPort: 8000
  internalPort: 8000
resources:
  limits: 
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 1m
    memory: 10Mi
